# Site Settings
lang: en
title: CMU Biorobotics
tagline: Biorobotics lab website
email: choset@andrew.cmu.edu
description: >
  The website for the Carnegie Mellon Biorobitcs lab
baseurl: "/lab_website"
url: "https://www.biorobotics.org"
permalink: pretty
#favicon: /path/to/favicon.png
# gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      hide_hero: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Biorobotics"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
      permalink: /posts/:year/:month/:day/:title/
      hide_hero: true
      summary: |

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

prose:
  rooturl: '_posts'
  siteurl: 'http://biorobotics.github.io/lab_website'
  relativeLinks: 'http://biorobotics.github.io/lab_website/links.jsonp'
  media: img/posts/
  metadata:
    _posts:
      - name: "image"
        field:
          label: "Image (Required)"
          element: "text"
          value: "img/posts/default.png"
      - name: "categories"
        field:
          element: "select"
          label: "Select Category (Required)"
          placeholder: "Choose Tags"
          options:
            - name: "Research"
              value: research
            - name: "Robots"
              value: robots
            - name: "Applications"
              value: applications
      - name: "title"
        field:
          element: "text"
          label: "Title (Required)"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Publish Date"
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Medical Robotics"
              value: "medical_robotics"
            - name: "Full Stack Autonomy"
              value: "full_stack_autonomy"
            - name: "Space Robotics"
              value: "space_robotics"
            - name: "Underwater Robotics"
              value: "underwater_robotics"
            - name: "Recycling Robotics"
              value: "recycling_robotics"
            - name: "Modular Robotics"
              value: "modular_robotics"
            - name: "Multi-Agent Planning"
              value: "multi-agent_planning"
            - name: "Manufacturing"
              value: "manufacturing"
            - name: "Locomoting Systems"
              value: "locomoting_systems"
            - name: "Confined Space Robotics"
              value: "confined_space_robotics"
            - name: "Expeditionary Robotics"
              value: "expeditionary_robotics"
            - name: "Skill Learning"
              value: "skill_learning"